### ISSUE TITLE
Error on creation of category link in 2.0b1

### ISSUE THREAD

**Issue by fiammybe** [ImpressModules/imtagging#6]
clicking on 'add category link' in the backend shows this error on ImpressCMS 2.0.0 beta 1:

`
This page cannot be displayed due to an internal error.

You can provide the following information to the administrators of this site to help them solve the problem:

Error: Call to undefined method icms_module_Object::dirname()

File: /home/fiammybe/domains/davidjanssens.be/public_html/beta/modules/imtagging/class/form/elements/imtaggingmoduleelement.php
Line: 24
Backtrace:
/libraries/icms/ipf/form/Base.php (160)
/libraries/icms/ipf/form/Base.php (53)
/libraries/icms/ipf/Object.php (373)
/modules/imtagging/admin/category_link.php (66)
/modules/imtagging/admin/category_link.php (113) `

**Comment by skenow** [comment]
Thanks for catching this - one of the legacy methods that has been removed. 

There are some other methods that will need to be addressed in this, too 
name()
mid()

**Comment by skenow** [comment]
Doing a review of this module, most of those conversions had already been done - this was a section that got missed.

**Comment by fiammybe** [comment]
Great news, I'm testing further
